#!/bin/bash

INSTALL_DIR=/usr/lib/rasterblocks

systemctl stop rasterblocks.service
systemctl disable "$INSTALL_DIR/rasterblocks.service"

rm -f "/var/lib/rasterblocks/config.json"
rmdir "/var/lib/rasterblocks"
