

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int rbPrussIoPru0Code[] =  {
     0x2a000000,
     0x240000e0,
     0xf100208c,
     0xe104208c,
     0x5701ecfd,
     0x5100ec02,
     0x2a000000,
     0x21000100 };

