

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int rbPrussIoPru1Code[] =  {
     0x241000e0,
     0xf1002088,
     0x5700e8fe,
     0x2a000000 };

