

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int rbPrussIoCode[] =  {
     0x240000e0,
     0x240002c1,
     0x24202081,
     0xe1002180,
     0x240010c1,
     0x24f01281,
     0x240004e2,
     0xe1002281,
     0x24567ae3,
     0x91043884,
     0x00e4e3e3,
     0x81083883,
     0x2400231f,
     0x2a000000 };

