#!/bin/bash

INSTALL_DIR=/usr/lib/stage-lights

pushd "$INSTALL_DIR/nodeserver"
npm install
popd

systemctl enable "$INSTALL_DIR/stage-lights-nodeserver.service"
systemctl start stage-lights-nodeserver.service
systemctl enable "$INSTALL_DIR/stage-lights.service"
#systemctl start stage-lights.service
