#!/bin/bash
echo GOODBYE WORLD
exit

INSTALL_DIR=/usr/lib/stage-lights

systemctl stop stage-lights.service
systemctl disable "$INSTALL_DIR/stage-lights.service"
systemctl stop stage-lights-nodeserver.service
systemctl disable "$INSTALL_DIR/stage-lights-nodeserver.service"

rm -r "$INSTALL_DIR/nodeserver/node_modules"
