#!/bin/bash
USERNAME=`id -un`
sudo mount --bind ./ ./precise-chroot/home/rasterblocks
sudo chroot precise-chroot /bin/bash -c "su \"$USERNAME\" -c \"cd /home/rasterblocks/; CROSS_BUILD=TRUE make bin/rasterblocks.target bin/rb-pruss-io-00A0.dtbo\""
sudo umount ./
