#!/bin/bash

INSTALL_DIR=/usr/lib/rasterblocks

systemctl stop rasterblocks-nodeserver.service
systemctl disable "$INSTALL_DIR/rasterblocks-nodeserver.service"

rm -rf "$INSTALL_DIR/nodeserver/node_modules"
